name: Trigger auto deployment for smartchatbot

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - 'Api/**'
    - '.github/workflows/smartchatbot-AutoDeployTrigger-d794e4f6-f10a-4f33-bf08-4ce860a72808.yml'

  # Allow manual trigger 
  workflow_dispatch:
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.SMARTCHATBOT_AZURE_CREDENTIALS }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v1
        with:
          appSourcePath: ${{ github.workspace }}/Api 
          registryUrl: hackyeah.azurecr.io
          registryUsername: ${{ secrets.SMARTCHATBOT_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.SMARTCHATBOT_REGISTRY_PASSWORD }}
          containerAppName: smartchatbot
          resourceGroup: HackYeah2023
          imageToBuild: hackyeah.azurecr.io/smartchatbot:${{ github.sha }}
          dockerfilePath: Dockerfile

     

